### Variables
@baseUrl = http://localhost:5000

### Register a user POST /auth/register
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "email": "gilgamesh@gmail.com",
    "password": "123123123",
    "name": "gilgamesh"
}

### Login a user POST /auth/login
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "gilgamesh@gmail.com",
    "password": "123123123",
    "name": "gilgamesh"
}

### Save token automatically 
@token = {{login.response.body.token}}

### Get all products /products
GET {{baseUrl}}/products/
Content-Type: application/json

### Get a single products /products/:id?category=category
GET {{baseUrl}}/products/?category=t-shirt
Content-Type: application/json

### Get user's cart /cart
GET {{baseUrl}}/cart
Authorization: Bearer {{token}}

### Add to cart /cart
POST {{baseUrl}}/cart 
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "product_id": 4,
    "quantity": 1
}

